name: DeathSwap
main: com.chaseoes.deathswap.DeathSwap
version: maven-version-number
description: Sethbling's deathswap gametype
softdepend: [Multiverse-Core, WorldEdit]
commands:
  deathswap:
    description: The central command for the DeathSwap plugin.
    usage: /<command> [args]
    aliases: [ds]